{
  "language": "node_js",
  "node_js": [
    "node"
  ],
  "script": [
    "npm run test",
    "npm run prettify ; echo 'checking if prettier changed something' ; git diff-index --name-only HEAD ; git diff HEAD ; git diff-index --quiet HEAD && echo 'ok' || (echo 'pretier modified contents, please run prettier locally and add changes. exitting...' && exit 1)"
  ],
  "before_deploy": "npm run pack",
  "deploy": {
    "provider": "releases",
    "api_key": {
      "secure": "LNxEb+qdBb8dqhrYWSpsfXWHrIDRVhXq/DPzhydogg5u7V765BMHMUAD2OEAPHiqkf9MFhaW+3eC+7ICFmd15uX23MnXjeQ8eoL5lNVGceK5cTow0Nv5wXStoOihQ7m4eXUtS7KUosGluqjLld89xJWUSXXJcBJcn4utWjynfrDTNy/5YkUpYzJK0oVGLcBrmjcNdjlCrq1Ivq1lOEWZnyGMPLbUpQRrZRTFH/PGvQ5UaySrxIkhNRtOa36NBc+B76z6DSs6IQQJXJMLbWq93UuasvVcvI1rCG9XOFL4RziAT41qrgQHqimeSYdUiWBc9rLeS2iGSBf6ZOolbzFTXECDkyS7n0nXe+m1sO+sImZTLr6dbkSQ+CrY7oxcWEP70TqU3kvI/HfZ7aJFhH0Ifp0adYWSSYBj5VJYlsorxAJj8lLJQGrzbxIL7CWkVMu7CBHczES5kKeo95RfwxXz4vrQe3fU7OLkCJ49gMS8gKwR0apJ6iKDN/FIh0oF6qSFHVSyIew97vY4h3NX+j5NHy9LERLvblDVKzgw8/150Sf1eFMJn6qkbNoKJf9vwivdT95fCGLUdBSFJhQWw7zG2eOsj7dUPeJ6nAvXZBkFBEnzatx7G302uVpIjWcxJCVkdLyWRY0lbM+8JxymJVx8yk927zYV6qvOAeY+RpEiln4="
    },
    "file_glob": true,
    "file": "packed/*",
    "skip_cleanup": true,
    "on": {
      "tags": true
    }
  },
  "after_script": [
    'npm run pack'
  ]
}
